anguage: elixir

elixir:
  - 1.11
otp_release:
  - 23.0

addons:
  apt:
    packages:
      - python3-pip

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - pip install -r requirements.txt
